### ISSUE TITLE
Switch to 1080p

### ISSUE THREAD

**Issue by silopolis** [ariemtech/piSignage#3]
re,

Can/how to switch to 1080p

**Comment by alejleva** [comment]
Hello,
Is 1080p now supported? How about in assets an option to add website viewing? 
Thank you.

**Comment by ariemtech** [comment]
Hi

We are supporting 1080p video and URL support in the coming release which we are working right now(planned date March 5). It is delayed due to our other priorities! 

Regards
Ravi

**Comment by ariemtech** [comment]
Current release supports switching between 1080p and 720p. Please note
1. If the player is controlled by the server change the settings under Group Tab. This will override the player settings upon sync.
2. If the player is standalone, you can change the display mode under settings from player web interface.
