### ISSUE TITLE
This player is powered by pisignage.com ticker

### ISSUE THREAD

**Issue by Magnekv** [ariemtech/piSignage#5]
Hi, uppdated to ver: 1.1.0/1.2.0  and now were getting a ticker saying ***this player is powered by pisignage.com*** how can we remove this?

**Comment by ariemtech** [comment]
Hi, When there is no license file this promotional ticker is shown. If you give me your cpuids of piSignage players, I can send you a license files or upload them to pisignage.com. 
As part of the new release we are coming up with a local server which could control players, act as API gateway for our customers to add features, zoning support, HTML/URL/livestream support. We are planning to open source server and price the player software one time at USD25. Only difference between free and licensed version is the ticker.

**Comment by Magnekv** [comment]
Hi, thank you very much for the quick reply and all the good information.  This looks very interesting!

Here are the cpu id:

00000000e5ab1a00

00000000bb025054

00000000e9229ac8



Yours sincerly
Magne Kvalsøren
Dagleg leiar | Konsulent
MK IT AS

Tlf. 412 97 643 | post@mkit.no<mailto:post@mkit.no>




Fra: Ravi Bail Bhat [mailto:notifications@github.com]
Sendt: 13. mars 2015 10:15
Til: ariemtech/piSignage
Kopi: Magne Kvalsøren
Emne: Re: [piSignage] This player is powered by pisignage.com ticker (#5)


Hi, When there is no license file this promotional ticker is shown. If you give me your cpuids of piSignage players, I can send you a license files or upload them to pisignage.com.
As part of the new release we are coming up with a local server which could control players, act as API gateway for our customers to add features, zoning support, HTML/URL/livestream support. We are planning to open source server and price the player software one time at USD25. Only difference between free and licensed version is the ticker.

**Comment by ariemtech** [comment]
what is your installation/username at pisignage.com, I will upload them there.

**Comment by Magnekv** [comment]
Mkitas

Login username : post@mkit.no


Fra: Ravi Bail Bhat [mailto:notifications@github.com]
Sendt: 13. mars 2015 10:45
Til: ariemtech/piSignage
Kopi: Magne Kvalsøren
Emne: Re: [piSignage] This player is powered by pisignage.com ticker (#5)


what is your installation/username at pisignage.com, I will upload them there.

**Comment by ariemtech** [comment]
Have uploaded the license files. If you reboot they should work. Otherwise you can download the files from URLs like http://pisignage.com/licenses/license_00000000e5ab1a00.txt

**Comment by Magnekv** [comment]
Thanks, working good!

Fra: Ravi Bail Bhat [mailto:notifications@github.com]
Sendt: 13. mars 2015 10:59
Til: ariemtech/piSignage
Kopi: Magne Kvalsøren
Emne: Re: [piSignage] This player is powered by pisignage.com ticker (#5)


Have uploaded the license files. If you reboot they should work. Otherwise you can download the files from URLs like http://pisignage.com/licenses/license_00000000e5ab1a00.txt

**Comment by ariemtech** [comment]
Every installation comes with 3 free licenses(players). After which please purchase licenses at www.pisignage.com/lp to avoid "player is powered by pisignage.com" ticker

**Comment by jaderiverazxc** [comment]
HI. Im having the same problem about the ticker in offline mode. how can i remove?

**Comment by navaneetharaopy** [comment]
Player needs to download license file from server. Before going to offline mode , make sure you register the player at pisignage.com and player comes online to download the license. After that it should work fine in offline mode also.

**Comment by lu1smanu3l** [comment]
Hi.

If I buy a player license, how many player devices can I connect to the local server?

**Comment by colloqi** [comment]
Hi

One, license is per player one time fee ($25)
