### ISSUE TITLE
Link view

### ISSUE THREAD

**Issue by PiXperience** [ariemtech/piSignage#6]
Hi,

I'm using the image from this link : 
https://dl.dropboxusercontent.com/u/166564018/pisignagepro.img.zip

I've got a problem, I cannot create a new Link.
When I click on Assets > Add > Add a link : it opens a popup with the parent window replicated into it.

G.

**Comment by ariemtech** [comment]
Thanks for pointing the issue, one of the template files is missing for showing popup and hence the issue. Will fix the issue and release an update. Meanwhile you can use pisignage.com server to upload the link.

**Comment by PiXperience** [comment]
Ok, I tried it, it send the link asset to the local Pi, but playing the playlist displays a Black Screen instead of the webpage...

**Comment by ariemtech** [comment]
Can I see the link address? Also does it have flash content or heavy JavaScript, both could be tough for pi to handle.

**Comment by PiXperience** [comment]
At the moment the link address just point a webpage with a simple text, I tried 9gag.com for example, but nothing better.
I already tried a previous version and webpages and assets management were working fine. I don't know why I've got this problem now.

**Comment by ariemtech** [comment]
Thanks, will check and get back.

**Comment by PiXperience** [comment]
I'll try with a previous pisignage.img I downloaded before. I'll try it tomorrow.

**Comment by PiXperience** [comment]
Ok, I get the 'previous img' I already tested and had working. BUT it appears to be the SAME: "pisignage_113_130.img"...
So I don't know why this one is not working.
Now I can't synchronize playlists and assets from pisignage.com.

**Comment by PiXperience** [comment]
I'm using another pi, and the synchronization is now ok, but I still have a black screen when displaying a link. And I cannot add a new link via local console.

**Comment by ariemtech** [comment]
if you have access to pi through ssh, you can goto /home/pi/media directory and edit the ".link" directly.

We will release another image in next 1-2 weeks which should fix this issue (adding link via local console)

**Comment by PiXperience** [comment]
Good to know, but it is stil displaying a black screen instead of the webpage. Pictures are working.

**Comment by ariemtech** [comment]
With the 1.1.4 release this issue is fixed
