### ISSUE TITLE
Unable to login!

### ISSUE THREAD

**Issue by explociti** [ariemtech/piSignage#7]
I entered 'pi' as the login and 'raspberry' as the password but apparently it they are incorrect login details. please can you tell me how to login.

**Comment by navaneetharaopy** [comment]
use 'pi' for both login and password.

**Comment by explociti** [comment]
Hi,
I have recently started using Pisignage and it perfectly suits my
requirements. During my use of Pisignage I noticed that the files that I
deploy are first downloaded onto the player/SDcard (not sure which) and
then they play on the screen. I want to know how to access and delete these
files from the player/SDcard.

regards,
Explociti

**Comment by navaneetharaopy** [comment]
1.check in directory '/home/pi/media' (using SSH). 
2.visit  *'http://[pi ip]:8000/assets'* from Chrome browser (use EDIT button on top to delete files)

**Comment by explociti** [comment]
Everytime I need to restart the player I have to reboot the system. And
reboot usually takes 3-4 mins. How to restart only the player?

**Comment by ariemtech** [comment]
answered in zendesk
